name: CI

on: 
  push:
    branches: 
      - source

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Pelican for GitHub Pages
        env:
          GIT_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          GH_PAGES_BRANCH: master
        uses: nelsonjchen/gh-pages-pelican-action@0.1.4
